# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastContact', models.FloatField(default=0)),
                ('exp_brca1', models.FloatField(default=0)),
                ('exp_usp1', models.FloatField(default=0)),
                ('vital_status', models.CharField(choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb_app.Patient')),
            ],
            options={
                'verbose_name_plural': 'Patient Data',
            },
        ),
    ]
